### ISSUE TITLE
delete user - method not allowed

### ISSUE THREAD

**Issue by SkowronekArt** [Bottelet/Flarepoint-crm#120]
I've spent much time to find a solution to remove the user. No good results :(

The form asks the admin, what needs to be done with the existing clients/tasks/leads and who to assign:
![handlde deletion](https://user-images.githubusercontent.com/29749820/60626671-cfc23f00-9deb-11e9-8c37-034a219dfebd.png)

The issue is in this file: [resources/views/users/index.blade.php](https://github.com/Bottelet/Flarepoint-crm/blob/master/resources/views/users/index.blade.php)

I've noticed, that the problem stays in the ajax. The `foreach` loop does not work here. When I try to fill the `select` `options` with Ajax - i receive this error:

`DataTables warning: Non-table node initialisation (SELECT). For more information about this error, please see http://datatables.net/tn/2`

Does anyone have an idea, how to assign other users to the tasks of the removed user? Please please help!

![Zrzut ekranu 2019-07-3 o 23 34 53](https://user-images.githubusercontent.com/29749820/60626491-3561fb80-9deb-11e9-906e-dd01a0fc5447.png)

**Comment by jhuebel** [comment]
Tomorrow is a holiday here in the United States. So I didn't plan on working on Flarepoint. But I'll be back at the office on Friday. I'll fix it then.

**Comment by jhuebel** [comment]
I'm reopening this issue. Although the user dropdown lists work in the modal  now, the modal itself doesn't seem to work. Maybe @Bottelet can shed some light on this. Has it ever worked? The fact that the submit button is labeled "Login" leads me to believe this may be something that was incomplete.

Regardless, since it's Javascript-- which I'm not great at-- it's going to take me a bit longer to resolve this.

**Comment by Bottelet** [comment]
@jhuebel This has worked before, I see the button, that's probably a copy paste error. It looks like the users variable might be empty, I would start by looking at that.

**Comment by jhuebel** [comment]
I've fixed the $users variable with the latest hotfix (1.3.4), but that
didn't resolve the problem. Clicking "Login" doesn't seem to do anything.

**Comment by jhuebel** [comment]
Found one problem, in particular, in
`resources/views/users/index.blade.php`:

```
handle_clients =  $("#handle_clients").val()
```

Note the missing semicolon at the end. So the click event for the "Login"
button doesn't fire. Even fixing this syntax error, jQuery returns a server
error. I thought it was related to the CSRF token, but I'm pretty sure that
the token is being properly added to the request headers.

**Comment by jhuebel** [comment]
Found one problem, in particular, in `resources/views/users/index.blade.php`:

```
handle_clients =  $("#handle_clients").val()
```

Note the missing semicolon at the end. So the click event for the "Login" button doesn't fire. Even fixing this syntax error, jQuery returns a server error. I thought it was related to the CSRF token, but I'm pretty sure that the token is being properly added to the request headers.

**Comment by jhuebel** [comment]
Just pushed a hotfix for the syntax error (and a little Javascript indentation cleanup), but that doesn't resolve the problem with jQuery sending the DELETE request to Laravel.

**Comment by jhuebel** [comment]
@SkowronekArt I'll have to look at this more over the weekend (hopefully). I hate to suggest it, but you may have to resort to manually updating the data and deleting the user within MySQL in the meantime.

**Comment by giesta** [comment]
app/Models/User.php:

1. Method clients() doesn't exist in this file
2. Methods moveTasks($user_id), moveLeads($user_id), moveClients($user_id) must be as these methods below:

![Screenshot from 2019-07-06 09-11-22](https://user-images.githubusercontent.com/47950470/60752423-1ec7ca00-9fce-11e9-997c-c6792c9e5c8c.png)
3.Method leads() must be like this
![image](https://user-images.githubusercontent.com/47950470/60752700-ab27bc00-9fd1-11e9-98e4-16bdbe4d1ea7.png)

4. That isn't enough, some users were deleted, some didn't. I couldn't figure out what is happening when I want to delete all tasks, leads and etc.

**Comment by giesta** [comment]
App/Models/User.php:
Method clients() doesn't exist. Leads and tasks have two foreign keys: user_assigned_id and user_created_id, I think that all those keys must be changed in the methods moveLeads and moveTasks.

**Comment by SkowronekArt** [comment]
Thank you for all your efforts, I really appreciate!

**Comment by jhuebel** [comment]
OK, I think I've come up with a solution. I should have it implemented today. It will also simplify the Delete User modal a little bit.

**Comment by jhuebel** [comment]
1.3.5 should resolve the User Delete modal problems. It was a little more complicated that I thought it would be. The modal window is also simplified. You can either choose "Delete All" from the dropdown lists or select a user to move the data to.

Here are some notes, though:

- If you choose to delete all clients, even tasks and leads assigned to a different user are deleted. So use that with caution. There is a tooltip on the modal that warns the you about this.
- If a task or lead was created by the user you are deleting, but is currently assigned to another user, the user that the task or lead was "created by" is modified. If you are deleting all the user's tasks or leads, then the "created by" is set to whoever the task or lead is currently assigned to. If you are moving the user's tasks or leads to another user, then the "created by" is set to the user you're moving the tasks and leads to.

Sorry for the delay on this, but it turned out to be more complicated than I anticipated. On the plus side, I'm now intimately familiar with using Bootstrap modals and mass-deleting relational data in Flarepoint. 🤣

**Comment by SkowronekArt** [comment]
works great!
