### ISSUE TITLE
cant view contacts

### ISSUE THREAD

**Issue by cyborix** [Bottelet/flarepoint-crm#125]
DataTables warning: table id=contacts-table - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

![image](https://user-images.githubusercontent.com/20562928/62126424-43714200-b2ed-11e9-9ca8-f3916e0a7be8.png)

**Comment by jhuebel** [comment]
Need more information than this. That's a generic error with DataTables and
really doesn't tell me anything more than that the JSON response was bad.

Please provide answers to the following questions, so I can troubleshoot
further:

1. What version are you running?
2. Is this a new install of Flarepoint CRM or did you upgrade from an
earlier version?
3. If you upgraded from an older version, what version?

We can go from there... I'll probably have more questions depending on how
you respond to these...

**Comment by jhuebel** [comment]
In addition to the questions above...

4. If you're upgrading, are you using git and following the instructions in the release notes?

**Comment by cyborix** [comment]
Thanks for responding. These are answers for the following queries
1. What version are you running?
->Laravel 5.4.36
2. Is this a new install of Flarepoint CRM or did you upgrade from an earlier version?
->It is new install of flarepoint.

Thanks,
jhuebel

**Comment by jhuebel** [comment]
This must be an installation problem, since it all worked for me. I'll admit that the installation documentation needs a lot of work. Here are the steps I just performed to install a clean copy of Flarepoint CRM on Ubuntu 19.04. I already had PHP 7.2, MySQL, NGINX, composer and nodejs installed. So you may need to sort through that before these steps can be completed.

First, clone a copy of Flarepoint CRM:
```
git clone https://github.com/bottelet/flarepoint-crm
cd flarepoint-crm
git checkout 1.3.6
```

Next, get all the dependencies and some other small things:
```
cp .env.example .env
composer install
npm install
php artisan key:generate
```

Next, create a MySQL database. I'll just have to assume you know how to do that. Once you've got your database created and know the username and password to access that database, you need to edit your .env file. Update the `DB_*` settings with your database settings. You should also change `APP_DEBUG` to **false** if you plan on running Flarepoint in production.

Once you've got your database settings straight, you can create the database tables and default admin user:
```
php artisan migrate --seed
```

If you want sample data, run this command:
```
php artisan db:seed --class=DummyDatabaseSeeder
```

Finally, it's time to fire up the Laravel test server and see if everything works:
```
php artisan serve
```
Then browse to http://localhost:8000/ . Login as admin@admin.com with the default password "admin123".

If everything works, then you can follow the Laravel deployment guide here to deploy the app using NGINX: [Laravel Deployment](https://laravel.com/docs/5.8/deployment)

I know that's for Laravel 5.8 (and Flarepoint is on 5.4), but it should work fine.

**Comment by cyborix** [comment]
Hi  jhuebel 
I did as mentioned above procedure and its not working properly   
![test](https://user-images.githubusercontent.com/20562928/62278646-20b66900-b466-11e9-9962-c7e4d44cf82d.gif)

**Comment by cyborix** [comment]
Hi,
I have followed the following steps. Still I am facing the same issue.

**Comment by cyborix** [comment]
Hi,
I have followed the following steps. Still I am facing the same issue.
here the video link

https://gofile.io/?c=3BI8sd

**Comment by giesta** [comment]
app/Http/Controllers/ContactsController.php method myData():
route must be changed from
![image](https://user-images.githubusercontent.com/47950470/62288862-fe245000-b465-11e9-9618-4794ebdd4206.png)
to
![image](https://user-images.githubusercontent.com/47950470/62288589-632b7600-b465-11e9-9f53-fd94b12f5bb2.png)

**Comment by jhuebel** [comment]
OK, I've made your suggested change in my code and will do some testing. Additionally, I'm going to make similar changes to some other "anyData" and "myData" methods to use the Laravel route() helper. This will make the coding style consistent.

I expect I'll commit the changes later today and tag them as version 1.3.7.

**Comment by cyborix** [comment]
i checked both but still same issue. 
![Screenshot from 2019-08-02 16-20-52](https://user-images.githubusercontent.com/20562928/62365323-698f2000-b541-11e9-809e-613b4593bec0.png)

![Screenshot from 2019-08-02 16-19-59](https://user-images.githubusercontent.com/20562928/62365303-62681200-b541-11e9-970b-e7f25dc0dfe8.png)

**Comment by jhuebel** [comment]
I haven't committed the changes yet. I'll commit them over the weekend.

**Comment by giesta** [comment]
You must change from 
![image](https://user-images.githubusercontent.com/47950470/62372190-7b6fc380-b53f-11e9-8ca2-2da3d021aeb4.png)
to
![image](https://user-images.githubusercontent.com/47950470/62372219-917d8400-b53f-11e9-904f-1eece5481776.png)

**Comment by jhuebel** [comment]
What file are you getting this last change from? I don't see what you're seeing.

/resources/views/contacts/index.blade.php and my.blade.php both have this in 1.3.6:
```
                {data: 'client_name', name: 'client_name'},
```

So your suggested change already exists in the current version. Please check to make sure you have checked out tag 1.3.6 before suggesting more changes: `git checkout 1.3.6`

**Comment by jhuebel** [comment]
After looking back through your replies, it would appear that you changed "client_name" to "client_id" at some point, then suggested that it be changed back to "client_name".

Sorry, but I'm considering closing this as WONTFIX. It seems you're making changes and then suggesting fixes to problems you've created yourself.

Any additional bugfixes you would like to make should be submitted as pull requests that can be properly reviewed, please.

**Comment by giesta** [comment]
Sorry, but my suggest was that @cyborix must change {data: 'client_name', **name: 'client_id'**}, I don't know why it is in his file😂
![image](https://user-images.githubusercontent.com/47950470/62385984-2f347b80-b55f-11e9-8097-a5fa53a9d252.png)

**Comment by cyborix** [comment]
sorry for the inconvenience😅😅 .. yeah  i changed  {data: 'client_name', name: '**client_id**'}

After changing  this  {data: 'client_name', name: '**client_id**'}  to {data: 'client_name', name: '**client_name**'} i am facing same ajax error

**Comment by cyborix** [comment]
sorry for the inconvenience😅😅 .. yeah  i changed  {data: 'client_name', name: '**client_id**'} just for testing.. i forget to change but still  cant fix the ERROR 

After changing  this  {data: 'client_name', name: '**client_id**'}  to {data: 'client_name', name: '**client_name**'} i am facing same ajax error

**Comment by jhuebel** [comment]
Changes have been pushed to the master branch. See release [1.3.7](https://github.com/Bottelet/flarepoint-crm/releases/tag/1.3.7) for more information.

**Comment by giesta** [comment]
@cyborix, what version is your PHP? If PHP 7.3, you should try this: https://github.com/laravel/framework/issues/26936

**Comment by giesta** [comment]
I tried to install this project on windows 10 with PHP 7.3. I had the same issue then I removed undefined 'operator' from 'compact' method and now it works 😊

**Comment by jhuebel** [comment]
I would suggest sticking with PHP 7.1 or 7.2 with the current version of
Flarepoint CRM, since it's based on Laravel 5.4.

That said, Flarepoint CRM 2.x will fully support PHP 7.3. But I don't have
a timeframe for when that will be released since I'm in the middle of
changing jobs and moving to another state here in the USA. So development
will slow significantly between now and the end of September.

**Comment by cyborix** [comment]
thanks guys @jhuebel @giesta  💐 

My PHP version 7.3.7
After removing **'operator'** from **'compact'** method its working @giesta
