### ISSUE TITLE
In All Department delete function not working.

### ISSUE THREAD

**Issue by MAliRazasaeed** [Bottelet/Flarepoint-crm#26]
Thanks for considering my requests. A little more bug. In setting/Role management/All Department /delete function doesn’t work. When I click delete it give exception error.
Image are Attached:

![image](https://cloud.githubusercontent.com/assets/21223565/19390414/752aeeec-9241-11e6-8ab4-1d601b94e1b3.png)

**Comment by Bottelet** [comment]
@MAliRazasaeed Sorry for the very late fix, been a bit busy, but this has been fixed in the last commits:
https://github.com/Bottelet/Flarepoint-crm/commit/39bc616af935ba8aa4301056d18fc01680dc7804
https://github.com/Bottelet/Flarepoint-crm/commit/3c5b865f7ba6a7039019f8eb690ae2e6857dc474
https://github.com/Bottelet/Flarepoint-crm/commit/5b368db51e7dc16772355ee61a2b4a8ef8ff170d

It is gonna require you to do a "composer update" when you have pulled down the changes, as there is a new version of entrust in use, maybe also do a composer dump-autoload
